### ISSUE TITLE
Mod causing game to fail after loading

### ISSUE THREAD

**Issue by Ryorama** [gigaherz/JsonThings#1]
Hey! I've been messing around with this mod and so far it seems like a really neat concept. After installing the 1.16.5 version on my other computer which I find odd considering it worked fine on my main PC. I'm not sure if it's the forge version I'm using or something else, but regardless I wanted to open this issue.

Game version: 1.16.5
Forge version: 36.2.0

[latest.log](https://github.com/gigaherz/JsonThings/files/7469542/latest.log)
[crash-2021-11-03_12.57.20-fml.txt](https://github.com/gigaherz/JsonThings/files/7469545/crash-2021-11-03_12.57.20-fml.txt)

**Comment by Ryorama** [comment]
Looks like my issue was with my custom thingpack and I was able to fix it.

**Comment by gigaherz** [comment]
Good to hear. I'll try to improve that error message so it indicates better *what* wasn't properly found.
