### ISSUE TITLE
json things appears to sometimes insert empty nbt tags on items after they're placed into a crafting grid

### ISSUE THREAD

**Issue by esotericist** [gigaherz/JsonThings#12]
for some reason, since i started running the new tinkers things addon for tinkers construct (which requires json things), i've started getting items with empty nbt tags attached:
![image](https://user-images.githubusercontent.com/1569754/213416978-c8231739-e733-4f00-9160-5861bc1f11d7.png)

this is obviously problematic for item stacking purposes.

issue reproduction process: pull a fresh stack of some material. use right-click to spread a set of stacks of 1 in a standard vanilla crafting grid. place the remaining stack (which never entered a crafting grid slot) back in inventory. shift-click items from the the crafting grid (NOT the resultant output item slot!) down to your inventory. behavior is erratic, it *seems* to vary both by basic item, and shift-click sequencing; some quantity will appear to merge with the existing stack, some quantity will end in a new stack.

demonstration video:
https://youtu.be/CDFAL57MtgM

testing instance:
forge 40.2.0, mantle 1.18.2-1.9.43, tconstruct 1.18.2-3.6.1.85, jsonthings 1.18.2-0.4.2, tinkers things 1.0 (fetched from the [releases in its repository](https://github.com/SlimeKnights/TinkersThings/releases/tag/v1.0.0))

for reasons unclear to me, i cannot replicate this problem with json things alone, or with json things, mantle, and tconstruct. the tinkers things jar MUST be present, but since it's essentially just a bunch of datapack stuff and a 'things' bundle for json things, i have to assume its only role is invoking some condition in json things to exhibit the error. mantle and tconstruct are possibly not required for the error to occur , but i didn't have it in me to try to assemble a specific test to verify that.

jei is present in the video, but it happens without it. it's just slightly less annoying to get mats from it than the creative inventory. no other mods present.

**Comment by gigaherz** [comment]
Hm, I'll take a look as soon as I can.

**Comment by esotericist** [comment]
knightminer informs me that this is actually a tinkers construct bug, which happens to be surfaced by tinkers things, and he'll be hotfixing it.

my apologies for pointing the finger at your mod for this.

**Comment by gigaherz** [comment]
Good to hear! I mean, that the bug has been identified.

**Comment by esotericist** [comment]
modded minecraft, always an adventure on multiple levels
