### ISSUE TITLE
[1.18.2] Error loading mods

### ISSUE THREAD

**Issue by sxjeru** [gigaherz/JsonThings#15]
#### I think this is not a TiC3 issue, so I put forward here firstly.

JsonThings-1.18.2-0.4.5/0.4.6
Mantle-1.18.2-1.9.43
TConstruct-1.18.2-3.6.2.92

[crash-2023-02-02_20.01.40-fml.txt](https://github.com/gigaherz/JsonThings/files/10568792/crash-2023-02-02_20.01.40-fml.txt)

![image](https://user-images.githubusercontent.com/20513115/216321517-319ba81f-6cfa-4940-8049-d82affd609bb.png)

```
Mod File: /C:/Users/Administrator/.minecraft/versions/1.18.2/mods/TConstruct-1.18.2-3.6.2.92.jar
	Failure message: Tinkers' Construct (tconstruct) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 3.6.2.92
	Mod Issue URL: https://github.com/SlimeKnights/TinkersConstruct/issues
	Exception message: java.lang.ClassNotFoundException: dev.gigaherz.jsonthings.things.serializers.ItemType
```

**Comment by gigaherz** [comment]
I think my recent updates have caused binary breaks that I didn't take into account.

**Comment by ffuentesm** [comment]
Does this have something to do with the new mandatory use of Rhino? 
![image](https://user-images.githubusercontent.com/44974827/216497278-65fc6f7f-a677-4fbb-8c90-b6920ef94c5f.png)

**Comment by gigaherz** [comment]
@ffuentesm Nope the rhino thing was a typo in my mods.toml, unrelated to the binary break.
@sxjeru I have looked into this and I don't think I can properly restore binary compatibility without making a mess for myself. hopefully it won't be too much trouble for KM to make a fix for this, cos I had to do another binary break today for the latest release... :S
