### ISSUE TITLE
[1.18.2] Crash/Incompat with Solar Flux Reborn

### ISSUE THREAD

**Issue by Phweeeee** [gigaherz/JsonThings#16]
Using Json Things (and Rhino) along with Solar Flux Reborn (And Hammer Lib) The game refuses to load. See below.

Latest: https://paste.gg/p/anonymous/fe8f30bc9a754549bcbc28ddc5e55125

Crash Rep: https://paste.gg/p/anonymous/038e51dcbe4c4bf8b38e7b28a9c3416a

**Comment by gigaherz** [comment]
I'll take a look as soon as I can. It may or may not be related to the breaking changes I introduced (didn't realize there were people actually using the mod's API when I made the changes)
