### ISSUE TITLE
Food items are eaten 2 at a time

### ISSUE THREAD

**Issue by maz3e** [gigaherz/JsonThings#19]
Added a basic food item to test this mod out, but I'm getting an issue with 2 items being eaten at once. This only seems to affect the item I added through a things pack.

I added the poison effect on the off chance it fixed the issue, but the problem also happens without it.

I also tried adding the content of the food block to _food/strawberry_jam.json_ and removing it from _item/strawberry_jam.json_ but that results in the item not being edible at all, which I'm not sure if that's intended or not.

{
  "type": "plain",
  "max_stack_size": 16,
  "food": {
    "nutrition": 1,
    "saturation": 2.0,
    "meat": false,
    "fast": false,
    "always_eat": false,
    "effects": [
      {
        "effect": "minecraft:poison",
        "duration": 1,
        "amplifier": 0,
        "visible": true,
        "show_particles": true,
        "show_icon": true      
      } 
    ]
  },
  "container": "bowl"
}

Video of the issue: https://user-images.githubusercontent.com/127639949/224521297-f8990d8f-ff05-4111-b637-43f870086a88.mp4

As a side note, I really appreciate this mod; I like making modpacks, and many mods don't have compat mods or miss things, so being able to add them in myself without having to write a whole mod to do it is great.

**Comment by gigaherz** [comment]
oh huh I missed this bug report, looking into it.

**Comment by gigaherz** [comment]
OOPS! I think I found why. Testing...

**Comment by gigaherz** [comment]
Should be fixed as of the latest respective versions (published, awaiting approval on CF).

**Comment by maz3e** [comment]
Confirmed fixed, thanks!
