### ISSUE TITLE
[1.20] Startup crash

### ISSUE THREAD

**Issue by MelanX** [gigaherz/JsonThings#24]
**MC** 1.20.1
**Forge** 47.1.0
**Json Things** 0.8.8

latest.log + crash report: https://gist.github.com/MelanX/6bd0ec196e5fa74ea556a1b4c7962ce4

How to reproduce?

0. Create a new Forge instance (not in dev env)
1. Install Json Things
2. Start game
3. Wait for it

This only happens in 1.20.1. The field the stacktracing is referencing to is `LOGGER`. Probably something related to https://github.com/gigaherz/JsonThings/blob/master/src/main/java/dev/gigaherz/jsonthings/things/parsers/ThingParser.java#L38

**Comment by gigaherz** [comment]
No it's this one. <https://github.com/gigaherz/JsonThings/blob/master/src/main/java/dev/gigaherz/jsonthings/things/parsers/SoundEventParser.java#L26> The two there. Oops!

**Comment by gigaherz** [comment]
It seems like it's a glitch in the reobf process, which doesn't realize static fields shouldn't inherit reobf renames from the parent class.
I have fixed it either way. Will release in a few hours when I can finish another thing.

**Comment by gigaherz** [comment]
Should be fixed in 0.9.0
