### ISSUE TITLE
Warning while loading mods

### ISSUE THREAD

**Issue by MelanX** [gigaherz/JsonThings#25]
**MC** 1.20.1
**Forge** 47.1.43
**JsonThings** 0.9.0

**How to reproduce**
1. Create a new instance with given versions
2. Start game
3. See this:
![image](https://github.com/gigaherz/JsonThings/assets/26039509/5baea979-f14d-4bce-9b2e-37dc34aa94d2)

Here's my latest.log: <https://gist.github.com/MelanX/fb685dfe0657b541ec7bf01a7697bda7>

I know, it's not critical, I still can play the game when pressing on the bottom button.

**Comment by gigaherz** [comment]
Hmm I guess it may be because the pack_format was 9 instead of 15? but it doesn't show up in dev so no idea.

**Comment by MelanX** [comment]
I changed the pack formats at each value to 15, it still shows this screen. As additional info: It lists all installed mods as "failed to load a valid ResourcePackInfo" when Json Things is installed. Not sure if this information is helpful at all.

**Comment by gigaherz** [comment]
o_O I'll look into it, maybe the warning is my fault somehow...

**Comment by gigaherz** [comment]
Yep was my fault. The code I had for loading ThingPacks from mod jars was outdated and caused the issue. Bringing it to parity with forge's logic that does the same for resource packs fixed it.
0.9.1 is up on CurseForge waiting for review.

**Comment by gigaherz** [comment]
Ah right, CF is broken, approval may take a bit longer.

**Comment by MelanX** [comment]
Awesome, thank you
