### ISSUE TITLE
[Suggestion] A way to copy an existing block's properties.

### ISSUE THREAD

**Issue by ZeroLevels** [gigaherz/JsonThings#26]
Just a way to copy an existing block's properties in case you're adding something similar and want to ensure continuity. Perhaps a command for a block being held in your main hand? Possibly even copy a JSON template of that block to your clipboard. It would be super helpful. :p

**Comment by ZeroLevels** [comment]
I'm dumb. Looked right past the "parent" thing. Ugh.

**Comment by gigaherz** [comment]
Heh. Still, you gave me the idea of having some client-side commands that generate templates. I have to look into it *someday*.
```
/jsonthings create pack <name>
/jsonthings pack set namespace <ns>
/jsonthings create item sword <name>
/jsonthings create blockset wood <name>
```
