### ISSUE TITLE
[Bug] Replaceable set to true by default for most block types.

### ISSUE THREAD

**Issue by ZeroLevels** [gigaherz/JsonThings#27]
**Minecraft 1.20.1
Forge 47.1.43**

The wiki states [here](https://github.com/gigaherz/JsonThings/blob/master/documentation/formats/Blocks.md#replaceable) that this property is set to **false** by default. Slabs seemed the be the only block type that didn't require an explicit _"replaceable": false_

Every other block was replaced when I would place another block against it until I specified not to do it. Love the concept of this mod. Keep it up! ♥

**Comment by gigaherz** [comment]
oops, will fix asap.
