### ISSUE TITLE
Make item dont afraid of fire and lava.

### ISSUE THREAD

**Issue by QikaHome** [gigaherz/JsonThings#29]
Just like netherite.
please add this feature

**Comment by gigaherz** [comment]
This feature already exists, if you use 1.20.1 or newer! You just have to add "fire_resistant" to the item json.
```
"fire_resistant": true 
```

![image](https://github.com/gigaherz/JsonThings/assets/685851/7829400e-2f2e-4ed4-8b2b-e39872321886)

**Comment by QikaHome** [comment]
Ok thanks.
Actually im making a mod works from 1.18.2 to 1.20.4 , but I have solved this by using functions.
BTW,may you add it to https://github.com/gigaherz/JsonThings/blob/master/documentation/formats/Items.md?
