### ISSUE TITLE
Can't specify a destroy_time that is smaller than 1.0

### ISSUE THREAD

**Issue by TheInfine** [gigaherz/JsonThings#3]
Setting a destroy_time that is smaller than 1.0 makes the block break instantly. This means that the fastest valid destroy_time is 1.0 which isn't fast enough in my case. This also affects sandwood leaves in the Sandwood example.

Minecraft: 1.18.1
Forge: 39.0.79
Json Things: 0.2.1

**Comment by gigaherz** [comment]
Nice catch. I'm not at home right now so will fix asap.

**Comment by TheInfine** [comment]
Same problem happens with explosion_resistance too.

**Comment by gigaherz** [comment]
Thanks. I probably misinterpreted what the value range was.

**Comment by gigaherz** [comment]
I'm home now, and I looked at it. I did indeed use the wrong types for this. I used integers, where it should be floating-point values.
Preparing fixed versions for 1.16.5, 1.17.1 and 1.18.1

**Comment by gigaherz** [comment]
Fixed as of 1.16.5-0.1.3, 1.17.1-0.1.3, and 1.18.1-0.2.2
