### ISSUE TITLE
[1.21] NeoForge crash on loading screen

### ISSUE THREAD

**Issue by Periam** [gigaherz/JsonThings#32]
After installing Json, it crash the game in the loading scren.
There is not crashlog, just the latest log.

NeoForge 21.0.56
JsonThings-1.21-0.12.0.jar
rhino-2100.2.5-build.41.jar

Logs

[latest.log](https://github.com/user-attachments/files/16103583/latest.log)

**Comment by gigaherz** [comment]
Hmm, that log doesn't say anything that all that would point to JsonThings.
Is there a debug.log? If you are using CurseForge as it seems like from the paths, you will need to enable it in the settings.
If a debug.log doesn't show any errors, you may need to enable the "show output window" option in the vanilla launcher curseforge opens when you launch a pack.

**Comment by Periam** [comment]
Hi, attached you will find the debug log

[debug.log](https://github.com/user-attachments/files/16110263/debug.log)

**Comment by gigaherz** [comment]
Thanks! I have looked at it but I don't see anything that indicates what the error may be can you join the Neoforge discord server and show this debug log on the user-support channel there?

**Comment by Periam** [comment]
I just posted on the user support channel
