### ISSUE TITLE
Crash because of Forge refactor

### ISSUE THREAD

**Issue by MelanX** [gigaherz/JsonThings#5]
The mod crashes/doesn't load with Forge 41.0.94+, I think you know why :)
Here the two related PRs:
- https://github.com/MinecraftForge/MinecraftForge/pull/8786 (guide linked in this PR)
- https://github.com/MinecraftForge/MinecraftForge/pull/8840

**Comment by gigaherz** [comment]
Yes I'm kinda waiting for there not to be a massive heat wave so I can focus.

**Comment by gigaherz** [comment]
Fixed in 0.6.0. It's waiting for approval at curseforge.
