### ISSUE TITLE
Sandwood door has invalid texture

### ISSUE THREAD

**Issue by MelanX** [gigaherz/JsonThings#6]
Version: 0.5.0
Forge: 41.0.35

As you can see, I look at the door from the test pack in your repository and it has an invalid texture.
![image](https://user-images.githubusercontent.com/26039509/180613332-6b21df8d-e0dc-43ee-ba11-f537b71e7ad7.png)

**Comment by gigaherz** [comment]
Fixed in 0.6.0. It's waiting for approval at curseforge.

![image](https://user-images.githubusercontent.com/685851/180641527-a49f9711-4dcb-41f3-a0d0-2e6919fe6670.png)
