### ISSUE TITLE
Unable to register items with custom armor materials

### ISSUE THREAD

**Issue by PyroBurnem** [gigaherz/JsonThings#7]
All is as in the title. When registering an item with a custom material, the parser is unable to recognise the custom material. Further experimentation with a armor material with an error and an item without errors and which includes the custom material does not throw an error for the material but for the item.

File structure is as shown below:
thingpack
- → pack
- - → armor_material
- - - → [evolving.json](https://github.com/gigaherz/JsonThings/files/9432067/evolving.txt)
- - → item
- - - → [evolving_chestplate.json](https://github.com/gigaherz/JsonThings/files/9432071/evolving_chestplate.txt)

Pardon the weird formatting. I also had to upload them as txt files due to github limitations.

My hypothesis is that items are being registered prior to armor material registration. The error in the evolving.json file is the exclusion of a required parameter, that being "armor" which i have renamed to "plomfret", which was caught when chestplate.json was removed from the files. However, with evolving_chestplate.json present, the item had been flagged out as the erroneous one instead, due to being unable to find the material.

The first crash details the armor material being caught for not having armor. The chestplate has yet to be included in the thingpack.
[crash-2022-08-26_17.37.11-fml.txt](https://github.com/gigaherz/JsonThings/files/9432041/crash-2022-08-26_17.37.11-fml.txt)
The second crash details the item being caught. The error for the armor material has not yet been rectified.
[crash-2022-08-26_17.39.17-fml.txt](https://github.com/gigaherz/JsonThings/files/9432043/crash-2022-08-26_17.39.17-fml.txt)

What should happen is that I should be able to make an armor material and use it in a custom item.

**Comment by PyroBurnem** [comment]
I can see another issue with this, particularly if a custom item is being used for the repair item within the armor material. So I'm going to see if I can get the exact name of the material that is being registered and hope that it's a problem with the naming scheme.

**Comment by gigaherz** [comment]
Huh... I'll look at it asap.

**Comment by gigaherz** [comment]
Uhhh... *looks at issue time* ... *looks at calendar* ... "asap" was a bit longer than intended. Sorry about that. My brain has really not in the right place for working on mods lately.
This has been fixed now, and will be included in the next update.
