### ISSUE TITLE
[Mod Interaction] JsonThings vs CraftTweaker: Crafting duplicates items

### ISSUE THREAD

**Issue by PyroBurnem** [gigaherz/JsonThings#9]
Do refer to [this video](https://user-images.githubusercontent.com/31893867/190865369-06722fbd-ac56-41fd-9a13-19d61b128410.mp4).

### The Issue
If CraftTweaker is installed and used to create a recipe with JsonThings custom items, the custom items duplicate. As a control group, I added a recipe that uses Dirt instead, an item not added by JsonThings. The recipe that uses Dirt did not duplicate the Dirt, whereas the recipe that uses the test item duplicated the test item. This is happening with fresh installs. I am not sure which mod is causing the issue, therefore I will open an issue in both mod's Githubs and link them to each other.

### Mods used
CraftTweaker: 1.18.2-9.1.189
JsonThings: 1.18.2-0.4.1
Forge: 40.1.80

### Steps to Reproduce
1. Add a JsonThings thingpack with at least 1 custom item.
2. Make a script that uses said item in the crafting input.
3. Run MC and craft the recipe with **at least 2 custom items** per slot that uses the custom item as listed in the script.
4. Click on the output to craft the item. The custom items are then duplicated.

### Relevant Files
[Thingpack used](https://github.com/CraftTweaker/CraftTweaker/files/9592094/test.zip)
[CraftTweaker Script used](https://gist.github.com/PyroBurnem/27c3d468add605d46f5da6a7f696dd66)
[The latest.log file](https://gist.github.com/PyroBurnem/3972f95c85eb25fcc55f60559a471f1c)

**Comment by PyroBurnem** [comment]
[Issue opened on CraftTweaker side.](https://github.com/CraftTweaker/CraftTweaker/issues/1556#issue-1376811277)

**Comment by gigaherz** [comment]
Hopefully the CT people know what's going on because I have no idea what the cause could be.

**Comment by gigaherz** [comment]
WAIT, I just saw the video, I completely misinterpreted what you meant.
This isn't an issue with the OUTUPT duplicating, but rather with the crafting table slots growing in size, in which case it's definitely my mod's fault.

**Comment by gigaherz** [comment]
Please try 0.4.2 for 1.18.2 or 0.7.1 for 1.19.2. (They may take a few minutes to get approved on curseforge)
If we are lucky the bug should be fixed.

**Comment by PyroBurnem** [comment]
I can confirm the bug has been fixed. Thank you!

**Comment by gigaherz** [comment]
Good to hear!
